Vagrant.configure("2") do |config|
  config.vm.define "spacewalkserver" do |spacewalkserver|
    spacewalkserver.vm.box = "bento/centos-6.7"
    spacewalkserver.vm.hostname = 'spacewalkserver'
    spacewalkserver.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.0.20"
    spacewalkserver.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "spacewalkserver"]
    spacewalkserver.vm.provision "shell", inline: <<-SHELL
      yum update
      yum install -y apache2 vim telnet git
      SHELL
    end
  end


  config.vm.define "spacewalkclient" do |spacewalkclient|
    spacewalkclient.vm.box = "bento/centos-6.7"
    spacewalkclient.vm.hostname = 'spacewalkclient'
    spacewalkclient.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.0.21"
    spacewalkclient.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "spacewalkclient"]
    end
  end

end