Vagrant.configure("2") do |config|
config.vm.provision "shell", inline: "apt-get install -y telnet git wget curl vim && echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGuCugFDxQfmM9LIeP6TOOh8sKUBbsduEvLzNeKhiLGZNoSg8sdRGOkp9jOWelIIW5jxDk9PB7dT49zEgk29OzRI8VyTKDYVx49H15hEmtITKWNrhpWu7VmmUr0h2E7aJ/0R7F1ybketIqmwq/EK8yNIjtLIv+PS9B0GiW7K1CZyg3jS7qB2IDxlfN6annU20CnC4XBsBnJDxHcElLNRMxpXWi5eWefY6E0Fy2b+EDPhGe5u5hoGwLiQIEWrnWYx9qQeAyJDOPBf+XJcXAOHo28xFZ/XCUB1UFnavrDWmjAZ3tthc/Er+tEV03T+71sFKRRytkmLPylKMXvA5ABJQp dk@typHooN' >>~/.ssh/authorized_keys"
  config.vm.define "puppetM" do |puppetM|
    puppetM.vm.box = "ubuntu/xenial64"
    puppetM.vm.hostname = 'puppetM'
    puppetM.vm.network :private_network, ip: "192.168.10.40"
    puppetM.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--name", "puppetM"]
  end
end


  config.vm.define "puppetS1" do |puppetS1|
    puppetS1.vm.box = "ubuntu/xenial64"
    puppetS1.vm.hostname = 'puppetS1'
    puppetS1.vm.network :private_network, ip: "192.168.10.41"
    puppetS1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "puppetS1"]
    end
  end

  config.vm.define "puppetS2" do |puppetS2|
    puppetS2.vm.box = "ubuntu/xenial64"
    puppetS2.vm.hostname = 'puppetS2'
    puppetS2.vm.network :private_network, ip: "192.168.10.42"
    puppetS2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "puppetS2"]
    end

end
end
