Vagrant.configure("2") do |config|
# config.vm.provision "shell", inline: "yum install -y epel-release telnet wget curl tree ntp vim net-tools && yum update -y && systemctl enable ntpd && sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config && systemctl restart sshd"
config.vm.provision "shell", inline: "yum install -y epel-release git telnet wget curl tree ntp vim net-tools && yum update -y && systemctl enable ntpd && sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config && systemctl restart sshd"
  config.vm.define "zabbixM" do |zabbixM|
    zabbixM.vm.box = "centos/7"
    # zabbixM.vm.box = "bento/ubuntu-18.04"
    zabbixM.vm.hostname = 'zabbixM'
    zabbixM.vm.network :private_network, bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.10.50"
    zabbixM.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--name", "zabbixM"]
  end
end


  config.vm.define "zabbixs1" do |zabbixs1|
    zabbixs1.vm.box = "centos/7"
    zabbixs1.vm.hostname = 'zabbixs1'
    zabbixs1.vm.network :private_network, bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.10.51"
    zabbixs1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--name", "zabbixs1"]
    end
  end

  config.vm.define "zabbixs2" do |zabbixs2|
    zabbixs2.vm.box = "centos/7"
    zabbixs2.vm.hostname = 'zabbixs2'
    zabbixs2.vm.network :private_network, bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.10.52"
    zabbixs2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--name", "zabbixs2"]
    end

end
end