Vagrant.configure("2") do |config|
  config.vm.define "nginx" do |nginx|
    nginx.vm.box = "ubuntu/xenial64"
    nginx.vm.hostname = 'nginx'
    nginx.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.0.40"
    nginx.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "nginx"]
      #config.vm.forwarded_port 80, 8080, auto_correct: true
      #config.vm.usable_port_range = (2200..2250)
    nginx.vm.provision "shell", inline: <<-SHELL
      echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGuCugFDxQfmM9LIeP6TOOh8sKUBbsduEvLzNeKhiLGZNoSg8sdRGOkp9jOWelIIW5jxDk9PB7dT49zEgk29OzRI8VyTKDYVx49H15hEmtITKWNrhpWu7VmmUr0h2E7aJ/0R7F1ybketIqmwq/EK8yNIjtLIv+PS9B0GiW7K1CZyg3jS7qB2IDxlfN6annU20CnC4XBsBnJDxHcElLNRMxpXWi5eWefY6E0Fy2b+EDPhGe5u5hoGwLiQIEWrnWYx9qQeAyJDOPBf+XJcXAOHo28xFZ/XCUB1UFnavrDWmjAZ3tthc/Er+tEV03T+71sFKRRytkmLPylKMXvA5ABJQp dk@typHooN" >>~/.ssh/authorized_keys
    SHELL
    end
  end
end