Vagrant.configure("2") do |config|
config.vm.provision "shell", inline: "yum install -y telnet wget curl vim traceroute"
  config.vm.define "icinga1" do |icinga1|
    icinga1.vm.box = "centos/7"
    icinga1.vm.hostname = 'icinga1'
    icinga1.vm.network :private_network, ip: "192.168.0.40"
    icinga1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "icinga1"]
  end
end


  config.vm.define "icinga2" do |icinga2|
    icinga2.vm.box = "centos/7"
    icinga2.vm.hostname = 'icinga2'
    icinga2.vm.network :private_network, ip: "192.168.0.41"
    icinga2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "icinga2"]
    end
end

end
