Vagrant.configure("2") do |config|
  config.vm.define "kaliserver" do |kaliserver|
    kaliserver.vm.box = "49thsd/kali-linux-2017.2-amd64"
    kaliserver.vm.hostname = 'kaliserver'
    kaliserver.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.10.10"
    kaliserver.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "kaliserver"]
      #config.vm.forwarded_port 80, 8080, auto_correct: true
      #config.vm.usable_port_range = (2200..2250)
    kaliserver.vm.provision "shell", inline: <<-SHELL
      wget http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
      rpm -Uvh epel-release-6*.rpm
      yum update
      yum install bash-completion bash-completion-extras -y
      yum install -y apache2 vim telnet git
      SHELL
    end
  end

end